
name: Hash functions
on: push
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashfiles('.github/workflows/*.yml') }}
