name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      LITERAL_NULL: ${{ null }}
      LITERAL_BOOLEAN: ${{ true }}
      LITERAL_NUMBER: ${{ 1234 }}
      LITERAL_STRING: ${{ 'hello' }}
      LITERAL_OMIT_STRING_: world
